import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./mixins.scss";
import Header from "./_components/Header/Header";
import { getHeaderData, getFooterData } from "./globalApi";
import Footer from "./_components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({children}: any) {

  const headerData = await getHeaderData();
  const footerData = await getFooterData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header headerData={headerData} />
        {children}
        <Footer footerData={footerData} />
      </body>
    </html>
  );
}
